# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = "https://blog.blessing.website/"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"

[languages]
[languages.zh]
title = 'Bless Blog'
[languages.zh.params]
homeSubtitle = "may the god bless you"
weight = 1

languageCode = "zh-cn"

title = "BLESS YOU"
enableGitInfo = true

hasCJKLanguage = true
pygmentsCodefences = true
pygmentsUseClasses = true

# rssLimit = 10

# copyright = "CHANGE ME"
enableEmoji = true

# disqusShortname = "CHANGE ME"

[params.author]
name = "BLESS"
about = "about"

[blackfriday]
# hrefTargetBlank = true
# noreferrerLinks = true
# nofollowLinks = true

[taxonomies]
tag = "tags"
# Categories are disabled by default.

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

description = "learning blog"
images = ["bg.jpg"]
themeColor = "#494f5c"

# homeSubtitle = "blog"
footerCopyright = "COPYRIGHT"
# bgImg = "bg"
# gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

justifyContent = true

relatedPosts = true
code_copy_button = true

homeSubtitlePrinter = true
scrollToTop = true
global_mathjax = false
readTime = true
readTimeSeparator = " "
legacyLayout = false
shareSocial = true

[[params.socialLinks]]
name = "github"
url = "https://github.com/Heironghuncheng/Heironghuncheng"

[menu]

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "About"
url = "about"
weight = 20

[services]
  [services.googleAnalytics]
    ID = 'G-PPKXV8KCVS'